import { RegionCarbonProfile } from "../types";

export const REGIONS: RegionCarbonProfile[] = [
  {
    id: "us-east-1",
    name: "US East (N. Virginia)",
    provider: "aws",
    carbonIntensity: 386,
    renewablePercent: 34,
    zone: "us",
    pricePerHourCPU: 0.048,
    pricePerHourGPU: 3.06,
    availabilityScore: 99,
    peakHours: [9, 10, 11, 14, 15, 16, 17],
  },
  {
    id: "us-west-2",
    name: "US West (Oregon)",
    provider: "aws",
    carbonIntensity: 136,
    renewablePercent: 71,
    zone: "us",
    pricePerHourCPU: 0.048,
    pricePerHourGPU: 3.06,
    availabilityScore: 97,
    peakHours: [10, 11, 12, 15, 16, 17, 18],
  },
  {
    id: "eu-west-1",
    name: "EU West (Ireland)",
    provider: "aws",
    carbonIntensity: 289,
    renewablePercent: 51,
    zone: "eu",
    pricePerHourCPU: 0.054,
    pricePerHourGPU: 3.30,
    availabilityScore: 98,
    peakHours: [8, 9, 10, 11, 14, 15, 16],
  },
  {
    id: "eu-north-1",
    name: "EU North (Stockholm)",
    provider: "aws",
    carbonIntensity: 8,
    renewablePercent: 98,
    zone: "eu",
    pricePerHourCPU: 0.056,
    pricePerHourGPU: 3.44,
    availabilityScore: 95,
    peakHours: [8, 9, 10, 14, 15],
  },
  {
    id: "ap-southeast-1",
    name: "Asia Pacific (Singapore)",
    provider: "aws",
    carbonIntensity: 431,
    renewablePercent: 22,
    zone: "asia",
    pricePerHourCPU: 0.058,
    pricePerHourGPU: 3.58,
    availabilityScore: 96,
    peakHours: [9, 10, 11, 13, 14, 15],
  },
  {
    id: "us-central1",
    name: "US Central (Iowa)",
    provider: "gcp",
    carbonIntensity: 424,
    renewablePercent: 51,
    zone: "us",
    pricePerHourCPU: 0.045,
    pricePerHourGPU: 2.93,
    availabilityScore: 98,
    peakHours: [9, 10, 11, 14, 15, 16],
  },
  {
    id: "northamerica-northeast1",
    name: "Montréal",
    provider: "gcp",
    carbonIntensity: 2,
    renewablePercent: 99,
    zone: "us",
    pricePerHourCPU: 0.048,
    pricePerHourGPU: 3.12,
    availabilityScore: 94,
    peakHours: [9, 10, 14, 15],
  },
  {
    id: "europe-west4",
    name: "Netherlands",
    provider: "gcp",
    carbonIntensity: 284,
    renewablePercent: 52,
    zone: "eu",
    pricePerHourCPU: 0.051,
    pricePerHourGPU: 3.22,
    availabilityScore: 97,
    peakHours: [8, 9, 10, 14, 15, 16],
  },
  {
    id: "eastus",
    name: "East US (Virginia)",
    provider: "azure",
    carbonIntensity: 379,
    renewablePercent: 36,
    zone: "us",
    pricePerHourCPU: 0.052,
    pricePerHourGPU: 3.19,
    availabilityScore: 99,
    peakHours: [9, 10, 11, 14, 15, 16, 17],
  },
  {
    id: "swedencentral",
    name: "Sweden Central",
    provider: "azure",
    carbonIntensity: 15,
    renewablePercent: 97,
    zone: "eu",
    pricePerHourCPU: 0.055,
    pricePerHourGPU: 3.38,
    availabilityScore: 94,
    peakHours: [8, 9, 14, 15],
  },
];

export const getRegionById = (id: string) => REGIONS.find((r) => r.id === id);

export const getCleanestRegions = (limit = 5) =>
  [...REGIONS].sort((a, b) => a.carbonIntensity - b.carbonIntensity).slice(0, limit);
